services:
  qbittorrent:
    image: linuxserver/qbittorrent:14.3.9
    container_name: qbittorrent
    environment:
      TZ: America/New_York
      UMASK: 000
    volumes:
      - config:/config
      - downloads:/downloads
    ports:
      - ${QBT_PORT:-6881}:${QBT_PORT:-6881}
      - ${QBT_PORT:-6881}:${QBT_PORT:-6881}/udp
      - 8017:8080
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G


volumes:
  downloads:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_HOST?err},rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nconnect=16,nfsvers=4
      device: ":/mnt/storage/downloads"
    name: "downloads"
  config:
    name: 'qbittorrent-config'
