version: "2.4"
services:
  qbittorrent:
    image: linuxserver/qbittorrent:14.3.5.99202106080759-7366-33e090cfcubuntu20.04.1-ls136
    container_name: qbittorrent
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
      WEBUI_PORT: 8080
      UMASK: 000
    volumes:
      - qbt_config:/config
      - downloads:/downloads
    ports:
      - ${PORT:-6881}:${PORT:-6881}
      - ${PORT:-6881}:${PORT:-6881}/udp
      - 8080:8080
    restart: unless-stopped
    dns: 1.1.1.1
    networks:
      - vlan

volumes:
  downloads:
    driver: local
    driver_opts:
      type: "cifs"
      o: "username=docker,password=${CIFS_PWD?err},uid=6000,gid=6000"
      device: "//${IP?err}/downloads"
    name: "downloads"
  qbt_config:
    name: 'qbittorrent_config'
    
networks:
  vlan:
    name: ipvlan
    driver: ipvlan
    driver_opts:
      parent: ${INTERFACE?err}
      ipvlan_mode: l2
    ipam:
      config:
        - subnet: '10.0.1.0/16'
          ip_range: '10.0.74.0/24'
          gateway: '10.0.1.1'