services:
  grav:
    image: linuxserver/grav:1.7.33
    container_name: grav
    ports:
      - 8007:80
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    labels:
      - docker-volume-backup.stop-during-backup=grav
    volumes:
      - data:/config
    restart: unless-stopped
    networks:
      - grav-net

  backup:
    image: offen/docker-volume-backup:v2.17.1
    container_name: grav-backup
    restart: unless-stopped
    environment:
      AWS_S3_BUCKET_NAME: backup.docker.data
      AWS_S3_PATH: grav
      AWS_ACCESS_KEY_ID: ${BACKUP_S3_ACCESS_KEY?err}
      AWS_SECRET_ACCESS_KEY: ${BACKUP_S3_SECRET_KEY?err}
      AWS_ENDPOINT: ${BACKUP_S3_ENDPOINT?err}
      AWS_ENDPOINT_PROTO: http
      BACKUP_STOP_CONTAINER_LABEL: grav
    volumes:
      - data:/backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - grav-net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

networks:
  grav-net:
    name: grav

volumes:
  data:
    name: grav-data