services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2022.07.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/New_York'
      PIHOLE_DNS_: 10.0.1.1;10.0.1.1
      DNSSEC: 'true'
      DNS_BOGUS_PRIV: 'true'
      DNS_FQDN_REQUIRED: 'true'
      IPv6: 'false'
      WEBPASSWORD: ${PIHOLE_PWD?err}
    volumes:
      - 'etc-pihole:/etc/pihole/'
      - 'etc-dnsmasq.d:/etc/dnsmasq.d/'
    restart: unless-stopped
    dns:
      - 127.0.0.1
    networks:
      - pihole-net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512MiB
        reservations:
          cpus: '0.5'
          memory: 256MiB

volumes:
  etc-pihole:
    name: 'pihole_etc-pihole'
  etc-dnsmasq.d:
    name: 'pihole_etc-dnsmasq.d'

networks:
  pihole-net:
    name: pihole
