services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.11.1-alpine
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    networks:
      - portainer-net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M

networks:
  portainer-net:
    name: portainer

volumes:
  data:
    name: portainer-data
