services:
  wordpress:
    image: wordpress:6.0.0-php8.1-apache
    container_name: wordpress
    depends_on:
      - wordpress-db
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: wordpress-db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${WP_DB_PWD?err}
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DEBUG: 1
    volumes:
      - wordpress:/var/www/html
      - export:/var/www/html/export
    networks:
      - wp-net

  wordpress-db:
    image: mysql:8.0.29
    container_name: wordpress-db
    restart: unless-stopped
    command:
      - mysqld
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${WP_DB_PWD?err}
      MYSQL_ROOT_PASSWORD: ${WP_DB_ROOT_PWD?err}
    volumes:
      - db:/var/lib/mysql
    networks:
      - wp-net
      - db-net

networks:
  wp-net:
    name: wordpress
  db-net:
    name: databases
    internal: true

volumes:
  wordpress:
    name: wordpress
  db:
    name: wordpress-db
  export:
    name: wordpress-export
