version: '3.4'
services:
  handbrake:
    image: jlesage/handbrake:v1.23.2
    container_name: handbrake
    environment:
      USER_ID: 1000
      GROUP_ID: 1000
      TZ: America/New_York
      UMASK: 000
      KEEP_APP_RUNNING: 1
      DISPLAY_WIDTH: 1920
      DISPLAY_HEIGHT: 1080
    ports:
      - "5885:5800"
    volumes:
      - "handbrake_config:/config:rw"
      - "downloads:/storage/downloads:ro"
      - "drop:/storage/drop:ro"
      - "media:/output:rw"
    tmpfs: 
      - /watch
      - /storage
    devices: 
      - '/dev/dri:/dev/dri'
    restart: unless-stopped
    networks:
      - handbrake_net

networks:
  handbrake_net:
    name: handbrake
      
volumes:
  handbrake_config:
    name: 'handbrake_config'
  downloads:
    driver: local
    driver_opts:
      type: cifs
      o: "addr=${IP?err},username=docker,password=${CIFS_PWD?err},uid=6000,gid=6000"
      device: "//${IP?err}/downloads"
    name: "downloads"
  drop:
    driver: local
    driver_opts:
      type: cifs
      o: "addr=${IP?err},username=docker,password=${CIFS_PWD?err},uid=6000,gid=6000"
      device: "//${IP?err}/drop"
    name: "drop"
  media:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${IP?err},rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14
      device: ":/mnt/storage/media"
    name: 'media'
