version: '3.4'
services:
  handbrake:
    image: jlesage/handbrake:latest
    container_name: handbrake
    build: .
    environment:
      TZ: America/New_York
      UMASK: 000
      USER_ID: 6000
      GROUP_ID: 6000
      SECURE_CONNECTION: 1
    ports:
      - "5800:5800"
    volumes:
      - "handbrake_config:/config:rw"
      - "downloads:/storage:rw"
      - "media:/output:rw"
    tmpfs: /watch
    group_add:
      - ${VIDEO_GROUP?err}
      - ${RENDER_GROUP?err}
    devices: 
      - '/dev/dri:/dev/dri'
#      - '/dev/sr0:/dev/sr0'
    restart: unless-stopped
      
volumes:
  handbrake_config:
    name: 'handbrake_config'
  downloads:
    driver: local
    driver_opts:
      type: "cifs"
      o: "username=docker,password=${CIFS_PWD?err},uid=6000,gid=6000"
      device: "//10.0.1.9/downloads"
    name: "downloads"
  media:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.1.9,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14
      device: ":/mnt/storage/media"
    name: 'media'
