version: "3.4"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/New_York'
      DNS1: 1.1.1.1
      DNS2: 'no'
      DNSSEC: 'true'
      DNS_BOGUS_PRIV: 'true'
      DNS_FQDN_REQUIRED: 'true'
      IPv6: 'false'
      DNSMASQ_USER: pihole
    # Volumes store your data between container upgrades
    volumes:
      - 'etc-pihole:/etc/pihole/'
      - 'etc-dnsmasq.d:/etc/dnsmasq.d/'
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1

volumes:
  etc-pihole:
    name: 'etc-pihole'
  etc-dnsmasq.d:
    name: 'etc-dnsmasq.d'
