version: "2.4"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/New_York'
      PIHOLE_DNS_: 1.1.1.1;1.0.0.1
      DNSSEC: 'true'
      DNS_BOGUS_PRIV: 'true'
      DNS_FQDN_REQUIRED: 'true'
      IPv6: 'false'
      DNSMASQ_USER: pihole
      WEBPASSWORD: ${PIHOLE_PWD?err}
      SERVER_IP: 10.0.1.31
    # Volumes store your data between container upgrades
    volumes:
      - 'etc-pihole:/etc/pihole/'
      - 'etc-dnsmasq.d:/etc/dnsmasq.d/'
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
    networks:
      pve1-ubuntu-vlan:
        ipv4_address: 10.0.3.3

volumes:
  etc-pihole:
    name: 'pihole_etc-pihole'
  etc-dnsmasq.d:
    name: 'pihole_etc-dnsmasq.d'

networks:
  pve1-ubuntu-vlan:
    name: pve1-ubuntu-vlan
    driver: ipvlan
    driver_opts:
      parent: ${INTERFACE?err}
      ipvlan_mode: l2
    ipam:
      config:
        - subnet: '10.0.1.0/16'
          ip_range: '10.0.1.0/16'
          gateway: '10.0.1.1'