version: "2.4"

services:
  pihole:
    container_name: pihole
    image: cbcrowe/pihole-unbound:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/New_York'
      PIHOLE_DNS_: 127.0.0.1#5335;127.0.0.1#5335
      DNSSEC: 'true'
      DNS_BOGUS_PRIV: 'true'
      DNS_FQDN_REQUIRED: 'true'
      IPv6: 'false'
      DNSMASQ_USER: pihole
      WEBPASSWORD: ${PIHOLE_PWD?err}
    volumes:
      - '${PIHOLE_DIR?err}/etc-pihole:/etc/pihole/'
      - '${PIHOLE_DIR?err}/etc-dnsmasq.d:/etc/dnsmasq.d/'
    restart: unless-stopped

volumes:
  etc-pihole:
    name: 'pihole_etc-pihole'
  etc-dnsmasq.d:
    name: 'pihole_etc-dnsmasq.d'
