version: "2.4"
services:
  traefik:
    container_name: traefik
    image: traefik:v2.4.8
    ports:
      - 8080:80
      - 8443:443
      - 8888:8080
    environment:
      TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT: 'false'
      TRAEFIK_PROVIDERS_DOCKER: 'true'
      TRAEFIK_PROVIDERS_DOCKER_NETWORK: ${DOCKER_NET?err}
      TRAEFIK_API_INSECURE: 'true'
      TRAEFIK_ENTRYPOINTS_HTTP_ADDRESS: ':80'
      TRAEFIK_ENTRYPOINTS_HTTPS_ADDRESS: ':443'
      TRAEFIK_CERTIFICATESRESOLVERS_STUDIOP_ACME_EMAIL: ${EMAIL?err}
      TRAEFIK_CERTIFICATESRESOLVERS_STUDIOP_ACME_STORAGE: /etc/traefik/acme.json
      TRAEFIK_CERTIFICATESRESOLVERS_STUDIOP_ACME_DNSCHALLENGE_PROVIDER: gcloud
      TRAEFIK_ACCESSLOG_FILEPATH: /var/log/access.log
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID?err}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY?err}
      AWS_REGION: ${AWS_REGION?err}
      AWS_HOSTED_ZONE_ID: ${AWS_HOSTED_ZONE_ID?err}
    volumes:
      - /var/log/traefik:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_data:/etc/traefik
    dns: 1.1.1.1
    networks:
      vlan:
        ipv4_address: 10.0.74.0
      proxy_net:
    restart: unless-stopped

volumes:
  traefik_data:
    name: 'traefik_data'

networks:
  proxy_net:
    name: ${DOCKER_NET?err}
    internal: true
  vlan:
    name: ipvlan
    driver: ipvlan
    driver_opts:
      parent: ${INTERFACE}
      ipvlan_mode: l2
    ipam:
      config:
        - subnet: '10.0.1.0/16'
          ip_range: '10.0.74.0/24'
          gateway: '10.0.1.1'
