version: "2.4"
services:
  traefik:
    container_name: traefik
    image: traefik:latest
    ports:
      - 8080:80
      - 8443:443
      - 8888:8080
    environment:
      TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT: 'false'
      TRAEFIK_PROVIDERS_DOCKER: 'true'
      TRAEFIK_PROVIDERS_DOCKER_NETWORK: ${DOCKER_NET?err}
      TRAEFIK_API_INSECURE: 'true'
      TRAEFIK_ENTRYPOINTS_HTTP_ADDRESS: ':80'
      TRAEFIK_ENTRYPOINTS_HTTPS_ADDRESS: ':443'
      TRAEFIK_CERTIFICATESRESOLVERS_STUDIOP_ACME_EMAIL: ${EMAIL?err}
      TRAEFIK_CERTIFICATESRESOLVERS_STUDIOP_ACME_STORAGE: /etc/traefik/acme.json
      TRAEFIK_CERTIFICATESRESOLVERS_STUDIOP_ACME_HTTPCHALLENGE_ENTRYPOINT: http
      TRAEFIK_ACCESSLOG_FILEPATH: /var/log/access.log
    volumes:
      - /var/log/traefik:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_data:/etc/traefik
    networks:
      - traefik_net
    restart: unless-stopped

  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    network_mode: "host"
    restart: always
    environment:
      F2B_DB_PURGE_AGE: 1m
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /var/log:/var/log:ro
      - ${FAIL2BAN_CONFIG_DIR?err}:/data

volumes:
  traefik_data:
    name: 'traefik_data'

networks:
  traefik_net:
    name: ${DOCKER_NET?err}