version: "2.4"
services:
  traefik:
    container_name: traefik
    image: traefik:v2.4.8
    ports:
      - 8080:80
      - 8443:443
      - 8888:8080
    environment:
      TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT: 'false'
      TRAEFIK_PROVIDERS_DOCKER: 'true'
      TRAEFIK_PROVIDERS_DOCKER_NETWORK: ${DOCKER_NET?err}
      TRAEFIK_API_INSECURE: 'true'
      TRAEFIK_ENTRYPOINTS_HTTP_ADDRESS: ':80'
      TRAEFIK_ENTRYPOINTS_HTTPS_ADDRESS: ':443'
      TRAEFIK_CERTIFICATESRESOLVERS_STUDIOP_ACME_EMAIL: ${EMAIL?err}
      TRAEFIK_CERTIFICATESRESOLVERS_STUDIOP_ACME_STORAGE: /etc/traefik/acme.json
      TRAEFIK_CERTIFICATESRESOLVERS_STUDIOP_ACME_DNSCHALLENGE_PROVIDER: gcloud
      TRAEFIK_ACCESSLOG_FILEPATH: /var/log/access.log
      GOOGLE_APPLICATION_CREDENTIALS: ${GCP_CREDENTIALS_FILE?err}
      GCE_PROJECT: ${GCP_PROJECT?err}
      GCE_TTL: 300
      GCE_PROPAGATION_TIMEOUT: 300
    volumes:
      - /var/log/traefik:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_data:/etc/traefik
    dns: 1.1.1.1
    networks:
      - vlan
      - traefik_net
    restart: unless-stopped

volumes:
  traefik_data:
    name: 'traefik_data'

networks:
  traefik_net:
    name: ${DOCKER_NET?err}
  vlan:
    name: ipvlan
    driver: ipvlan
    driver_opts:
      parent: ${INTERFACE?err}
      ipvlan_mode: l2
    ipam:
      config:
        - subnet: '10.0.1.0/16'
          ip_range: '10.0.74.0/24'
          gateway: '10.0.1.1'