version: "2.4"
services:
  traefik:
    container_name: traefik
    image: traefik:latest
    ports:
      - 8080:80
      - 8443:443
      - 8888:8080
    environment:
      TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT: 'false'
      TRAEFIK_PROVIDERS_DOCKER: 'true'
      TRAEFIK_PROVIDERS_DOCKER_NETWORK: 'apps.studiop.page'
      TRAEFIK_API_INSECURE: 'true'
      TRAEFIK_ENTRYPOINTS_HTTP_ADDRESS: ':80'
      TRAEFIK_ENTRYPOINTS_HTTPS_ADDRESS: ':443'
      TRAEFIK_CERTIFICATESRESOLVERS_STUDIOP_ACME_EMAIL: ${EMAIL?err}
      TRAEFIK_CERTIFICATESRESOLVERS_STUDIOP_ACME_STORAGE: /etc/traefik/acme.json
      TRAEFIK_CERTIFICATESRESOLVERS_STUDIOP_ACME_HTTPCHALLENGE_ENTRYPOINT: http
      TRAEFIK_PROVIDERS_FILE_FILENAME: /etc/traefik/traefik_dynamic.yml
      TRAEFIK_PROVIDERS_FILE_WATCH: 'false'
      TRAEFIK_ACCESSLOG_FILEPATH: /var/log/access.log
      TRAEFIK_ACCESSLOG_FILTERS_STATUSCODES: 400-499,500-599
    volumes:
      - /var/log/traefik:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_data:/etc/traefik
    networks:
      - apps_studiop_page
    restart: unless-stopped

volumes:
  traefik_data:
    name: 'traefik_data'

networks:
  apps_studiop_page:
    name: "apps.studiop.page"