version: '3.4'

services:
    nextcloud:
        image: nextcloud:21.0.2
        container_name: nextcloud
        restart: unless-stopped
        ports:
            - 8880:80
        depends_on: 
            - nextcloud_db
            - redis
        volumes:
            - cloud_data:/data
            - nc_data:/var/www/html
        environment:
            MYSQL_PASSWORD: ${NC_DB_PWD?err}
            MYSQL_DATABASE: nextcloud
            MYSQL_USER: nextcloud
            MYSQL_HOST: nextcloud-db
            REDIS_HOST: nextcloud-redis
            NEXTCLOUD_ADMIN_USER: admin
            NEXTCLOUD_ADMIN_PASSWORD: ${NC_ADMIN_PWD?err}
            NEXTCLOUD_TRUSTED_DOMAINS: ${NC_DOMAINS?err}
            NEXTCLOUD_DATA_DIR: /data
        networks:
            - nc-net
    
    nextcloud_db:
        image: mariadb:10.6.1
        container_name: nextcloud-db
        restart: unless-stopped
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-read-only-compressed=OFF
        volumes:
            - cloud_db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${NC_DB_ROOT_PWD?err}
            MYSQL_PASSWORD: ${NC_DB_PWD?err}
            MYSQL_DATABASE: nextcloud
            MYSQL_USER: nextcloud
        networks:
            - nc-net
            - db-net
        
    redis:
        image: redis:6.2.4
        container_name: nextcloud-redis
        restart: unless-stopped
        volumes:
            - redis:/data
        networks:
            - nc-net

    collabora:
        image: collabora/code:6.4.9.3
        container_name: collabora
        restart: unless-stopped
        ports:
            - 9980:9980
        environment: 
            extra_params: --o:ssl.enable=false
        cap_add: 
            - MKNOD
        networks:
            - nc-net

networks:
    db-net:
        name: databases
        internal: true
    nc-net:
        name: nextcloud

volumes:
    redis:
        name: redis
    nc_data:
        name: nextcloud_data
    cloud_db:
        name: nextcloud_db
    cloud_data:
        name: cloud_data
        driver: local
        driver_opts: 
            type: nfs
            o: addr=${IP?err},rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14
            device: ":/mnt/storage/drive"
