version: '3.4'

services:
    adminer:
        container_name: adminer
        image: adminer:4.8.1
        restart: unless-stopped
        ports:
          - 8088:8080
        networks:
          - adminer_net
          - db-net

networks:
  adminer_net:
  db-net:
      name: databases
      internal: true