version: '3.4'

services:
    adminer:
        container_name: adminer
        image: adminer:4.8.1
        restart: unless-stopped
        ports:
          - 8088:8080
        networks:
          - db-net

networks:
    db-net:
        name: databases
        internal: true