version: "2.4"
services:
  nginx-reverse-proxy:
    container_name: nginx-reverse-proxy
    image: jwilder/nginx-proxy:alpine
    ports:
      - 8080:80
      - 8443:443
    restart: unless-stopped
    volumes:
      - "html:/usr/share/nginx/html"
      - "dhparam:/etc/nginx/dhparam"
      - "vhost:/etc/nginx/vhost.d"
      - "certs:/etc/nginx/certs"
      - "/run/docker.sock:/tmp/docker.sock:ro"
    networks:
      - 'apps_studiop_page'

  letsencrypt:
    container_name: letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    volumes:
      - "html:/usr/share/nginx/html"
      - "dhparam:/etc/nginx/dhparam"
      - "vhost:/etc/nginx/vhost.d"
      - "certs:/etc/nginx/certs"
      - "/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      NGINX_PROXY_CONTAINER: "nginx-reverse-proxy"
      DEFAULT_EMAIL: ${EMAIL?err}
    restart: unless-stopped
    depends_on:
      - "nginx-reverse-proxy"
    networks:
      - 'apps_studiop_page'

  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    restart: "unless-stopped"
    environment:
      TZ: America/New_York
    volumes:
      - fail2ban_data:/data
      - "/var/log:/var/log:ro"
      - "/var/lib/docker/5000.5000/containers/:/container-logs/:ro"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - apps_studiop_page

volumes:
  fail2ban_data:
    name: 'fail2ban_data'
  html:
    name: "nginx_html"
  dhparam:
    name: "nginx_dhparam"
  vhost:
    name: "nginx_vhost"
  certs:
    name: "nginx_certs"

networks:
  apps_studiop_page:
    name: 'apps.studiop.page'
