version: "3.4"

services:
  wordpress:
    image: wordpress:5.7.2
    container_name: wordpress
    depends_on:
      - wordpress-db
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: wordpress-db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${WP_DB_PWD?err}
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: "wp_"
      WORDPRESS_DEBUG: 1
    volumes:
      - wordpress:/var/www/html
      - wp-export:/var/www/html/wp_export
    networks:
      - wp-net

  wordpress-db:
    image: mysql:8.0.25
    container_name: wordpress-db
    restart: unless-stopped
    command:
      [
        "mysqld",
        "--character-set-server=utf8",
        "--collation-server=utf8_unicode_ci",
      ]
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${WP_DB_PWD?err}
      MYSQL_ROOT_PASSWORD: ${WP_DB_ROOT_PWD?err}
    volumes:
      - wp-db:/var/lib/mysql
    networks:
      - wp-net
      - db-net

  # wordpress-cli:
  #   depends_on:
  #     - wordpress
  #     - wordpress-db
  #   user: xfs
  #   container_name: wordpress-cli
  #   image: wordpress:cli
  #   environment:
  #     WORDPRESS_DB_HOST: wordpress-db
  #     WORDPRESS_DB_USER: wordpress
  #     WORDPRESS_DB_PASSWORD: $WP_DB_PWD
  #     WORDPRESS_DB_NAME: wordpress
  #   volumes:
  #     - wordpress:/var/www/html

networks:
  wp-net:
    name: wordpress
  db-net:
    name: databases

volumes:
  wordpress:
    name: "wordpress"
  wp-db:
    name: "wordpress_db"
  wp-export:
    name: "wordpress_export"
