version: "3.4"
services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    ports:
      - 9696:8096
    environment:
      TZ: America/New_York
      VIRTUAL_HOST: ${VIRTUAL_HOST?err}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST?err}
      VIRTUAL_PORT: 9696
    volumes:
      - jellyfin_config:/config:rw
      - media:/data:rw
    group_add:
      - ${VIDEO_GROUP?err}
      - ${RENDER_GROUP?err}
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    networks:
      - 'apps_studiop_page'

networks:
  apps_studiop_page:
    name: 'apps.studiop.page'

volumes:
  jellyfin_config:
    name: 'jellyfin_config'
  media:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.1.2,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14
      device: ":/mnt/storage/media"
    name: 'media'