version: "3.4"
services:
  jellyfin:
    image: linuxserver/jellyfin:10.6.4-1-ls95
    container_name: jellyfin
    ports:
      - 9696:8096
    environment:
      TZ: America/New_York
      PUID: 1000
      PGID: 1000
    volumes:
      - jellyfin_config:/config:rw
      - media:/data:rw
    tmpfs: /config/data/transcodes
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.port=8096
      - traefik.http.routers.jellyfin.entrypoints=https
      - traefik.http.routers.jellyfin.rule=Host(`${HOST?err}`) && PathPrefix(`/jellyfin`)
      - traefik.http.routers.jellyfin.tls.certresolver=studiop
    networks:
      - jellyfin_net
      - proxy_net

networks:
  jellyfin_net:
  proxy_net:
    name: ${DOCKER_NET?err}
    internal: true

volumes:
  jellyfin_config:
    name: 'jellyfin_config'
  media:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${IP?err},rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14
      device: ":/mnt/storage/media"
    name: 'media'
