version: "3.4"
services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    ports:
      - 9696:8096
    environment:
      TZ: America/New_York
    volumes:
      - jellyfin_config:/config:rw
      - media:/data:rw
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.port=8096
      - traefik.http.routers.jellyfin.entrypoints=https
      - traefik.http.routers.jellyfin.rule=Host(`apps.studiop.page`) && PathPrefix(`/jellyfin`)
      - traefik.http.routers.jellyfin.tls.certresolver=studiop
    networks:
      - 'jellyfin_net'

networks:
  jellyfin_net:
    name: ${DOCKER_NET?err}

volumes:
  jellyfin_config:
    name: 'jellyfin_config'
  media:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.1.2,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14
      device: ":/mnt/storage/media"
    name: 'media'