services:
  firefox:
    container_name: firefox${FF_NUM?err}
    image: jlesage/firefox:v1.18.0
    ports:
      - ${FF_PORT?err}:5800
    volumes:
      - config:/config
      - downloads:/config/downloads
    restart: unless-stopped
    environment:
      TZ: America/New_York
      UMASK: 000
      KEEP_APP_RUNNING: 1
      DISPLAY_WIDTH: 1920
      DISPLAY_HEIGHT: 1080
    networks:
      - ff-net
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 4G
        reservations:
          cpus: 0.5
          memory: 2G
    shm_size: 2G

networks:
  ff-net:
    name: firefox

volumes:
  config:
    name: firefox${FF_NUM?err}-config
  downloads:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_HOST?err},rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nconnect=16
      device: ":/mnt/storage/downloads"
    name: "downloads"
