version: "2.4"
services:
  firefox:
    container_name: firefox${FF_NUM?err}
    image: jlesage/firefox:v1.18.0
    ports:
      - ${FF_PORT?err}:5800
    volumes:
      - ff_config:/config
      - downloads:/config/downloads
    restart: unless-stopped
    environment:
      USER_ID: 1000
      GROUP_ID: 1000
      TZ: America/New_York
      UMASK: 000
      KEEP_APP_RUNNING: 1
      DISPLAY_WIDTH: 1920
      DISPLAY_HEIGHT: 1080
    security_opt:
      - seccomp:seccomp.json
    networks:
      - ff_net
    cpus: 2
    mem_limit: 4g
    mem_reservation: 2g
    shm_size: 4g

networks:
  ff_net:
    name: firefox

volumes:
  ff_config:
    name: firefox${FF_NUM?err}_config
  downloads:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${IP?err},rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14
      device: ":/mnt/storage/downloads"
    name: "downloads_v2"
