version: "2.4"
services:
  firefox:
    container_name: firefox
    image: jlesage/firefox:v1.17.1
    ports:
      - 5800:5800
    volumes:
      - /dev/shm:/dev/shm
      - ff_config:/config
      - downloads:/config/downloads
    restart: unless-stopped
    environment:
      USER_ID: 1000
      GROUP_ID: 1000
      TZ: America/New_York
      UMASK: 000
      KEEP_APP_RUNNING: 1
      DISPLAY_WIDTH: 1920
      DISPLAY_HEIGHT: 1080
    security_opt:
      - seccomp:./seccomp.json
    dns: 1.1.1.1
    networks:
      - vlan

networks:
  vlan:
    name: ipvlan
    driver: ipvlan
    driver_opts:
      parent: ${INTERFACE?err}
      ipvlan_mode: l2
    ipam:
      config:
        - subnet: "10.0.1.0/16"
          ip_range: "10.0.74.0/24"
          gateway: "10.0.1.1"

volumes:
  ff_config:
    name: firefox_config
  downloads:
    driver: local
    driver_opts:
      type: "cifs"
      o: "username=docker,password=${CIFS_PWD?err},uid=6000,gid=6000"
      device: "//${IP?err}/downloads"
    name: "downloads"
