version: "2.4"
services:
  firefox:
    container_name: firefox
    image: jlesage/firefox:v1.17.1
    ports:
      - 5858:5800
    volumes:
      - /dev/shm:/dev/shm
      - ff_config:/config
      - downloads:/config/downloads
    restart: unless-stopped
    environment:
      USER_ID: 1000
      GROUP_ID: 1000
      TZ: America/New_York
      UMASK: 000
      KEEP_APP_RUNNING: 1
      DISPLAY_WIDTH: 1920
      DISPLAY_HEIGHT: 1080
    security_opt:
      - seccomp:seccomp.json
    networks:
      - ff_net

networks:
  ff_net:
    name: firefox

volumes:
  ff_config:
    name: firefox_config
  downloads:
    driver: local
    driver_opts:
      type: "cifs"
      o: "username=docker,password=${CIFS_PWD?err},uid=6000,gid=6000"
      device: "//${IP?err}/downloads"
    name: "downloads"
