services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.11.1-alpine
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    networks:
      - portainer-net

networks:
  portainer-net:
    name: portainer

volumes:
  data:
    name: portainer-data
